# Workspace that is used for this operation. Most of time, this is done on local.
workspace: releasemaven
# release version that is used to generate changelog. This need to be changed every time
version: 1.5.19
# github organization as the token is bound to the org in changelog generator. This
# means that you can only release multiple repositories within the same org each time.
organization: networknt
# You can skip checkout if you are sure that the code in workspace are the latest and
# you just want to repeat the release process due to some environmental issue before.
skip_checkout: false
# You can skip the merge step is this has been done in the previous execution.
skip_merge: false
# You can skip the last release step so that you can double check the merged result.
skip_release: true
# clone and switch to develop branch / checkout and pull from develop branch
checkout:
  - branch: develop
    repository:
    - git@github.com:networknt/light-4j.git
    - git@github.com:networknt/openapi-parser.git
    - git@github.com:networknt/light-rest-4j.git
    - git@github.com:networknt/light-graphql-4j.git
    - git@github.com:networknt/light-hybrid-4j.git
    - git@github.com:networknt/light-codegen.git
    - git@github.com:networknt/light-eventuate-4j.git
    - git@github.com:networknt/light-tram-4j.git
    - git@github.com:networknt/light-saga-4j.git
    - git@github.com:networknt/light-session-4j.git
    - git@github.com:networknt/light-proxy.git
    - git@github.com:networknt/light-router.git
    - git@github.com:networknt/light-oauth2.git
    - git@github.com:networknt/light-example-4j.git
    - git@github.com:networknt/light-docker.git
    - git@github.com:networknt/light-doc.git
    - git@github.com:networknt/light-bot-config.git
    - git@github.com:networknt/light-config-test.git
    - git@github.com:networknt/light-bot.git
    - git@github.com:lightapi/light-config-server.git
    - git@github.com:networknt/microservices-framework-benchmark.git
    - git@github.com:networknt/model-config.git
    - git@github.com:networknt/light-portal.git
    - git@github.com:networknt/react-schema-form.git
    - git@github.com:networknt/light-workflow-4j.git
    - git@github.com:networknt/light.git
    - git@github.com:networknt/swagger-bundler.git
    - git@github.com:networknt/http2client-benchmark.git
    - git@github.com:networknt/json-schema-validator-perftest.git
    - git@github.com:networknt/microbenchmark.git
    - git@github.com:networknt/react-schema-form-rc-select.git
    - git@github.com:networknt/light-config-prod.git
    - git@github.com:networknt/react-file-manager.git
    - git@github.com:networknt/light-commerce.git
    - git@github.com:networknt/light-cms.git
# merge develop to master and check in master for above repositories.
# It assumes that you always merge into master branch to release.
# Some of the repositories above are not going to be release but simple merge from
# develop to master in order to sync with other repo's release.
merge:
# generate changelog.md from github issues and check in
# release to maven central
# merge the changelog.md to develop branch
# publish the release to github repository
release:
  - light-4j
  - openapi-parser
  - light-rest-4j
  - light-graphql-4j
  - light-hybrid-4j
#  - light-codegen
  - light-eventuate-4j
  - light-tram-4j
  - light-saga-4j
  - light-session-4j
#  - light-proxy
#  - light-router
#  - light-oauth2
